org.dupot.easyflatpak.yml
fix application name
fix display application in home page
=> fix application name and bugfix

org.dupot.easyflatpak.yml
update italian traduction
update code quality
update screenshot on flathub
=> improve and code quality

org.dupot.easyflatpak.yml
Improve darkmode
Add back button on application page
Update detailed application display
=> Improve and bugfix

org.dupot.easyflatpak.yml
when type , switch to search page
=> update to 2.9.0

org.dupot.easyflatpak.yml
=> update italian traduction

org.dupot.easyflatpak.yml
update application database
update application icons
=> fix update page

org.dupot.easyflatpak.yml
add option to allow to delete all application data during uninstallation
=> add feature

org.dupot.easyflatpak.yml
Fix FR traductions
improve side menu
=> updates and bugfix

org.dupot.easyflatpak.yml
modify DB: add new column: last release
use this new column to order home page application list in application page, display last release list
add traduction for links, screenshots and last releases
=> update and bug fixes

org.dupot.easyflatpak.yml
=> add new feature: scope installation

org.dupot.easyflatpak.yml
bugfix on updates availables page
use window manager host
some icons update
=> bugfix and improvments

org.dupot.easyflatpak.yml
=> add progrss bar

org.dupot.easyflatpak.yml
update logo
move localizations to json assets files
=> add feature to update all with one button

org.dupot.easyflatpak.yml
in category view and installed application view
=> add button to switch display list/grid

org.dupot.easyflatpak.yml
=> new design

org.dupot.easyflatpak.yml
update darkmode button text color
=> update italian translation

org.dupot.easyflatpak.yml
new search page
bug fix
new cart feature
=> new page system

org.dupot.easyflatpak.yml
=> improve darkmode

org.dupot.easyflatpak.yml
=> upgrade flutter and dependencies

org.dupot.easyflatpak.yml
github issues fixed
bug fix in search page
=> improve windows manager

.gitignore, build.sh, check.sh, org.dupot.easyflatpak.yml
- update application icons
- update database
- When update description or data cache application, update last application icon too
- Update italian traduction
=> Many updates

org.dupot.easyflatpak.yml
bug fix https://github.com/imikado/dupotEasyFlatpak/issues/31
=> layout improvment

org.dupot.easyflatpak.yml
bugfix https://github.com/imikado/dupotEasyFlatpak/issues/24 
add brazilian traduction
=> bug fix + improvment

org.dupot.easyflatpak.yml
Add feature to choose scope during installation
Scope installation bugfix
Uninstation scope bugfix
=> Improvment and bugfix

org.dupot.easyflatpak.yml
add loading page traduction
update application database
=> improvment

org.dupot.easyflatpak.yml
Bugfix when try to install application with recipe Code improvment
Switch to log application in place of print
=> Bugfix and improvment

org.dupot.easyflatpak.yml
- update application database
- improve search (search in title, summary and description)
=> database update + improvment

org.dupot.easyflatpak.yml
bugfix for some applications without release timestamp bugfix in search: can't find some applications like gimp, now search in description too
=> Bufix and improvments

org.dupot.easyflatpak.yml
- add bundle feature
- fix update page
=> add feature and bugfix

org.dupot.easyflatpak.yml
fix on application update page
update application database from flathub api
=> bugfix and update

org.dupot.easyflatpak.yml
add parameter to choose when search between flathub api and local database update applications database
=> add new feature to search with flathub api
